using System.Linq;

namespace ExpressionEvaluatorForDotNet
{
    public class HL7V22SegmentURD
    {
        public readonly HL7V2Message message;

        public string Id { get { return @"URD"; } }

        public string SegmentId { get { return @"URD"; } }
        
        public string LongName { get { return @"Results/update Definition"; } }
        
        public string Description { get { return @"The URD segment is used in sending unsolicited updates about orders and results.  It's purpose is similar to that of the QRD segment, but from the results/unsolicited update point of view. Some of the fields have parallels in the QRD segment"; } }
        
        public string Sample { get { return @""; } }

        public IList<string> Chapters 
        { 
            get 
            {
                return new[]
                    {
                        "CH_02",
                    };
            }
        }

        public IList<HL7V2FieldData> Fields 
        { 
            get 
            {
                return new[]
                        {
                            new HL7V2FieldData
                        {
                            Id = @"URD.1",
                            Type = @"Field",
                            Position = @"URD.1",
                            Name = @"R/U Date / Time",
                            Length = 26,
                            Usage = @"O",
                            Rpt = @"1",
                            DataType = @"TS",
                            DataTypeName = @"Time Stamp",
                            TableId = null,
                            TableName = null,
                            Description = @"date and time the update was generated by the application program",
                            Sample = @"",
                            FieldDatas = 
                        new HL7V2FieldData
                        {
                            Id = @"URD.1.1",
                            Type = @"Component",
                            Position = @"URD.1.1",
                            Name = @"Time Of An Event",
                            Length = 0,
                            Usage = @"O",
                            Rpt = @"1",
                            DataType = @"ST",
                            DataTypeName = @"String Data",
                            TableId = null,
                            TableName = null,
                            Description = null,
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.1.2",
                            Type = @"Component",
                            Position = @"URD.1.2",
                            Name = @"Degree Of Precision",
                            Length = 0,
                            Usage = @"O",
                            Rpt = @"1",
                            DataType = @"ST",
                            DataTypeName = @"String Data",
                            TableId = null,
                            TableName = null,
                            Description = null,
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.2",
                            Type = @"Field",
                            Position = @"URD.2",
                            Name = @"Report Priority",
                            Length = 1,
                            Usage = @"O",
                            Rpt = @"1",
                            DataType = @"ID",
                            DataTypeName = @"Coded Value",
                            TableId = @"0109",
                            TableName = @"REPORT PRIORITY",
                            Description = @"priority associated with this report or update.  Refer to table 0109 - report priority for valid codes",
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.3",
                            Type = @"Field",
                            Position = @"URD.3",
                            Name = @"R/U Who Subject Definition",
                            Length = 20,
                            Usage = @"R",
                            Rpt = @"*",
                            DataType = @"ST",
                            DataTypeName = @"String Data",
                            TableId = null,
                            TableName = null,
                            Description = @"definition of the subject, or who the report is about",
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.4",
                            Type = @"Field",
                            Position = @"URD.4",
                            Name = @"R/U What Subject Definition",
                            Length = 3,
                            Usage = @"O",
                            Rpt = @"*",
                            DataType = @"ID",
                            DataTypeName = @"Coded Value",
                            TableId = @"0048",
                            TableName = @"WHAT SUBJECT FILTER",
                            Description = @"describes the kind of information that is provided in the report.  Valid codes are the type of transaction inquiry.  Refer to table 0048 - what subject filter for valid codes",
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.5",
                            Type = @"Field",
                            Position = @"URD.5",
                            Name = @"R/U What Department Code",
                            Length = 20,
                            Usage = @"O",
                            Rpt = @"*",
                            DataType = @"ST",
                            DataTypeName = @"String Data",
                            TableId = null,
                            TableName = null,
                            Description = @"possible contents include test number, procedure number, drug code, item number, order number, etc.  The contents of this field are determined by the contents of the previous field. This field could contain multiple occurrences separated by repetition delimiters",
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.6",
                            Type = @"Field",
                            Position = @"URD.6",
                            Name = @"R/U Display / Print Locations",
                            Length = 20,
                            Usage = @"O",
                            Rpt = @"*",
                            DataType = @"ST",
                            DataTypeName = @"String Data",
                            TableId = null,
                            TableName = null,
                            Description = @"a list of the locations to which the report should be distributed",
                            Sample = @"",
                            FieldDatas = null
                        },
                        
                        new HL7V2FieldData
                        {
                            Id = @"URD.7",
                            Type = @"Field",
                            Position = @"URD.7",
                            Name = @"R/U Results Level",
                            Length = 1,
                            Usage = @"O",
                            Rpt = @"1",
                            DataType = @"ID",
                            DataTypeName = @"Coded Value",
                            TableId = @"0108",
                            TableName = @"QUERY RESULTS LEVEL",
                            Description = @"used to control level of detail in results.  Refer to table 0108 - query results level for valid codes.  Default level is T for full results",
                            Sample = @"",
                            FieldDatas = null
                        },
                        };
            }
        }

        public HL7V22SegmentURD(HL7V2Message message)
        {
            this.message = message;
        }

        internal HL7V22Field rUDateTime;

public HL7V22Field RUDateTime
{
    get
    {
        if (rUDateTime != null)
        {
            return rUDateTime;
        }

        rUDateTime = new HL7V22Field
        {
            field = message[@"URD"][1],
            Id = @"URD.1",
            Type = @"Field",
            Position = @"URD.1",
            Name = @"R/U Date / Time",
            Length = 26,
            Usage = @"O",
            Rpt = @"1",
            DataType = @"TS",
            DataTypeName = @"Time Stamp",
            TableId = null,
            TableName = null,
            Description = @"date and time the update was generated by the application program",
            Sample = @"",
        };

        

        

        

        return rUDateTime;
    } 
}
internal HL7V22Field reportPriority;

public HL7V22Field ReportPriority
{
    get
    {
        if (reportPriority != null)
        {
            return reportPriority;
        }

        reportPriority = new HL7V22Field
        {
            field = message[@"URD"][2],
            Id = @"URD.2",
            Type = @"Field",
            Position = @"URD.2",
            Name = @"Report Priority",
            Length = 1,
            Usage = @"O",
            Rpt = @"1",
            DataType = @"ID",
            DataTypeName = @"Coded Value",
            TableId = @"0109",
            TableName = @"REPORT PRIORITY",
            Description = @"priority associated with this report or update.  Refer to table 0109 - report priority for valid codes",
            Sample = @"",
        };

        

        

        

        return reportPriority;
    } 
}
internal HL7V22Field rUWhoSubjectDefinition;

public HL7V22Field RUWhoSubjectDefinition
{
    get
    {
        if (rUWhoSubjectDefinition != null)
        {
            return rUWhoSubjectDefinition;
        }

        rUWhoSubjectDefinition = new HL7V22Field
        {
            field = message[@"URD"][3],
            Id = @"URD.3",
            Type = @"Field",
            Position = @"URD.3",
            Name = @"R/U Who Subject Definition",
            Length = 20,
            Usage = @"R",
            Rpt = @"*",
            DataType = @"ST",
            DataTypeName = @"String Data",
            TableId = null,
            TableName = null,
            Description = @"definition of the subject, or who the report is about",
            Sample = @"",
        };

        

        

        

        return rUWhoSubjectDefinition;
    } 
}
internal HL7V22Field rUWhatSubjectDefinition;

public HL7V22Field RUWhatSubjectDefinition
{
    get
    {
        if (rUWhatSubjectDefinition != null)
        {
            return rUWhatSubjectDefinition;
        }

        rUWhatSubjectDefinition = new HL7V22Field
        {
            field = message[@"URD"][4],
            Id = @"URD.4",
            Type = @"Field",
            Position = @"URD.4",
            Name = @"R/U What Subject Definition",
            Length = 3,
            Usage = @"O",
            Rpt = @"*",
            DataType = @"ID",
            DataTypeName = @"Coded Value",
            TableId = @"0048",
            TableName = @"WHAT SUBJECT FILTER",
            Description = @"describes the kind of information that is provided in the report.  Valid codes are the type of transaction inquiry.  Refer to table 0048 - what subject filter for valid codes",
            Sample = @"",
        };

        

        

        

        return rUWhatSubjectDefinition;
    } 
}
internal HL7V22Field rUWhatDepartmentCode;

public HL7V22Field RUWhatDepartmentCode
{
    get
    {
        if (rUWhatDepartmentCode != null)
        {
            return rUWhatDepartmentCode;
        }

        rUWhatDepartmentCode = new HL7V22Field
        {
            field = message[@"URD"][5],
            Id = @"URD.5",
            Type = @"Field",
            Position = @"URD.5",
            Name = @"R/U What Department Code",
            Length = 20,
            Usage = @"O",
            Rpt = @"*",
            DataType = @"ST",
            DataTypeName = @"String Data",
            TableId = null,
            TableName = null,
            Description = @"possible contents include test number, procedure number, drug code, item number, order number, etc.  The contents of this field are determined by the contents of the previous field. This field could contain multiple occurrences separated by repetition delimiters",
            Sample = @"",
        };

        

        

        

        return rUWhatDepartmentCode;
    } 
}
internal HL7V22Field rUDisplayPrintLocations;

public HL7V22Field RUDisplayPrintLocations
{
    get
    {
        if (rUDisplayPrintLocations != null)
        {
            return rUDisplayPrintLocations;
        }

        rUDisplayPrintLocations = new HL7V22Field
        {
            field = message[@"URD"][6],
            Id = @"URD.6",
            Type = @"Field",
            Position = @"URD.6",
            Name = @"R/U Display / Print Locations",
            Length = 20,
            Usage = @"O",
            Rpt = @"*",
            DataType = @"ST",
            DataTypeName = @"String Data",
            TableId = null,
            TableName = null,
            Description = @"a list of the locations to which the report should be distributed",
            Sample = @"",
        };

        

        

        

        return rUDisplayPrintLocations;
    } 
}
internal HL7V22Field rUResultsLevel;

public HL7V22Field RUResultsLevel
{
    get
    {
        if (rUResultsLevel != null)
        {
            return rUResultsLevel;
        }

        rUResultsLevel = new HL7V22Field
        {
            field = message[@"URD"][7],
            Id = @"URD.7",
            Type = @"Field",
            Position = @"URD.7",
            Name = @"R/U Results Level",
            Length = 1,
            Usage = @"O",
            Rpt = @"1",
            DataType = @"ID",
            DataTypeName = @"Coded Value",
            TableId = @"0108",
            TableName = @"QUERY RESULTS LEVEL",
            Description = @"used to control level of detail in results.  Refer to table 0108 - query results level for valid codes.  Default level is T for full results",
            Sample = @"",
        };

        

        

        

        return rUResultsLevel;
    } 
}

    }
}
